//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Admins = new HashSet<Admin>();
            this.Careers = new HashSet<Career>();
            this.SvcProfiles = new HashSet<SvcProfile>();
            this.Skills = new HashSet<Skill>();
            this.Platforms = new HashSet<Platform>();
        }
    
        public int profileID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string linkedinURL { get; set; }
        public string pictureURL { get; set; }
        public string portfolioURL { get; set; }
        public string highestEducation { get; set; }
        public string relocationYN { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string city { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<Career> Careers { get; set; }
        public virtual ICollection<SvcProfile> SvcProfiles { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<Platform> Platforms { get; set; }
    }
}
