//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcProfile
    {
        public int svcProfileID { get; set; }
        public int profileID { get; set; }
        public int svcTypeID { get; set; }
        public System.DateTime billingDate { get; set; }
        public string billingCode { get; set; }
        public string billingMethod { get; set; }
        public Nullable<System.DateTime> svcStartDate { get; set; }
        public Nullable<System.DateTime> svcEndDate { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual SvcType SvcType { get; set; }
    }
}
