//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcType
    {
        public SvcType()
        {
            this.SvcProfiles = new HashSet<SvcProfile>();
        }
    
        public int svcTypeID { get; set; }
        public string svcName { get; set; }
        public decimal svcCharge { get; set; }
        public int svcWeeks { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<SvcProfile> SvcProfiles { get; set; }
    }
}
